name: My First Actions Workflow

run-name: ${{ github.workflow }}-${{ github.run_number }}

on:
  workflow_dispatch: # Manual trigger

  issues: # Issue was created
    types: [opened]
  
jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Say Hello
        run: echo "Hello, GitHub Actions!"

      - if: ${{ github.event.issue }}
        run: |
          gh issue comment ${{ github.event.issue.number }} -b "Welcome to my repo! Thanks for opening this issue"
        env:
          GITHUB_TOKEN: ${{ github.token }}

  reuse-say-hello:
    uses: ./.github/workflows/reusable.yaml
    with:
      greeting: 'Welcome'
