name: OIDC Sample

on: [ workflow_dispatch ]

permissions:
  contents: read
  id-token: write
  
jobs:
  demo-oidc:
    runs-on: ubuntu-latest
    steps:
      - uses: azure/login@v2
        name: Log in to Azure using OIDC
        with:
          client-id: ${{ vars.OIDC_CLIENT_ID }}
          tenant-id: ${{ vars.OIDC_TENANT }}
          subscription-id: ${{ vars.OIDC_SUBSCRIPTION }}

      - run: |
          az acount show
